// Build the MCP App widgets: bundle each React widget (React included) into one
// self-contained HTML file, then emit it as a TS string module the Worker can
// import. Run via `pnpm run build:widgets` (wired into the main build).
//
// Why a codegen step: the Cloudflare Worker has no filesystem at runtime, so the
// widget HTML must be a string baked into the Worker bundle. esbuild inlines
// React + the component into one IIFE; we drop that into an HTML shell and write
// it to src/mcp/widgets/<name>.generated.ts. Self-contained → empty CSP, no CDN.

import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const widgetsDir = resolve(here, "../src/mcp/widgets");

// Add a widget here to ship it. `entry` is bundled; `out` exports `cssVar`-named
// HTML; `cssVar` is the exported constant name the Worker imports.
const WIDGETS = [
  {
    name: "Decision Grid",
    entry: resolve(widgetsDir, "DecisionGridApp.tsx"),
    out: resolve(widgetsDir, "decisionGrid.generated.ts"),
    exportName: "DECISION_GRID_HTML",
  },
];

// Shared widget chrome. Styling stays self-contained (no external fonts/CSS) and
// adapts to the host's colour scheme via prefers-color-scheme, mirroring the
// existing frameworks widget.
const CSS = /* css */ `
  :root {
    --fg:#1a1a1a; --muted:#6b7280; --card:#fff; --border:#e5e7eb;
    --accent:#4f46e5; --grid:#eceef2; --bg:transparent;
  }
  @media (prefers-color-scheme: dark){
    :root{ --fg:#f3f4f6; --muted:#9ca3af; --card:#1f2023; --border:#34363b;
      --accent:#8b8bf5; --grid:#2a2c31; }
  }
  *{ box-sizing:border-box; }
  body{ margin:0; padding:12px; color:var(--fg); background:var(--bg);
    font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; }
  .empty{ color:var(--muted); font-size:13px; padding:16px 4px; }
  .head h1{ font-size:15px; font-weight:650; margin:0 0 2px; }
  .head .q{ font-size:12.5px; color:var(--muted); margin:0 0 10px; }
  /* grid layout around the square plane: poles + axis labels frame it */
  .board{ display:grid; gap:4px; align-items:center; justify-items:center;
    grid-template-columns:auto auto 1fr auto;
    grid-template-areas:
      ". . yhi ."
      "ylabel ylo plane yhi2"
      ". . xrow ."; }
  .yhi{ grid-area:yhi; font-size:11px; color:var(--muted); }
  .ylo{ grid-area:ylo; font-size:11px; color:var(--muted);
    writing-mode:vertical-rl; transform:rotate(180deg); }
  .yhi2{ display:none; }
  .ylabel{ grid-area:ylabel; font-size:11.5px; font-weight:600;
    writing-mode:vertical-rl; transform:rotate(180deg); }
  .plane{ grid-area:plane; position:relative; width:100%; aspect-ratio:1/1;
    max-width:340px; border:1px solid var(--border); border-radius:12px;
    background:var(--card); overflow:hidden; touch-action:none; }
  .axisV{ position:absolute; left:50%; top:0; bottom:0; width:1px; background:var(--grid); }
  .axisH{ position:absolute; top:50%; left:0; right:0; height:1px; background:var(--grid); }
  .xrow{ grid-area:xrow; display:flex; justify-content:space-between; width:100%;
    max-width:340px; font-size:11px; color:var(--muted); }
  .xlo,.xhi,.xlabel{ display:inline; }
  .xlabel{ font-weight:600; color:var(--fg); }
  .chip{ font:inherit; font-size:12px; cursor:pointer; border-radius:999px;
    border:1px solid var(--border); background:var(--card); color:var(--fg);
    padding:4px 10px; }
  .chip.placed{ position:absolute; transform:translate(-50%,50%);
    border-color:var(--accent); box-shadow:0 1px 3px rgba(0,0,0,.18);
    cursor:grab; touch-action:none; white-space:nowrap; }
  .tray{ display:flex; flex-wrap:wrap; gap:6px; align-items:center; margin-top:12px; }
  .trayLabel{ font-size:11.5px; color:var(--muted); }
  .foot{ margin-top:14px; }
  .send{ font:inherit; font-size:13px; font-weight:600; cursor:pointer;
    border:none; border-radius:10px; padding:8px 14px;
    background:var(--accent); color:#fff; }
`;

function htmlShell(js) {
  // Note: the bundled JS is appended verbatim. esbuild output never contains
  // a literal "</script>" sequence, so no escaping is needed here.
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>${CSS}</style>
</head>
<body>
<div id="root"><div class="empty">Loading…</div></div>
<script type="module">${js}</script>
</body>
</html>`;
}

function tsModule(exportName, html) {
  return (
    `// AUTO-GENERATED by scripts/build-widgets.mjs — do not edit by hand.\n` +
    `// Self-contained HTML (React bundled in) for an MCP App widget; served by\n` +
    `// src/mcp/server.ts as a UI resource. Regenerate with \`pnpm run build:widgets\`.\n` +
    `/* eslint-disable */\n` +
    `export const ${exportName} = ${JSON.stringify(html)};\n`
  );
}

for (const w of WIDGETS) {
  const result = await build({
    entryPoints: [w.entry],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    jsx: "automatic",
    minify: true,
    write: false,
    define: { "process.env.NODE_ENV": '"production"' },
    logLevel: "warning",
  });
  const js = result.outputFiles[0].text;
  const html = htmlShell(js);
  await writeFile(w.out, tsModule(w.exportName, html), "utf8");
  const kb = (Buffer.byteLength(html, "utf8") / 1024).toFixed(0);
  console.log(`built ${w.name} → ${w.out.split("/").slice(-1)[0]} (${kb} KB)`);
}
