#!/usr/bin/env bash
#
# One-time setup for a PERMANENT Cloudflare named tunnel that exposes the local
# DEC dev Worker at a fixed HTTPS hostname — for connecting the MCP app to
# ChatGPT (and later the OAuth/Connect flow). See docs/todo/Auth.md §11.
#
# Idempotent: safe to re-run. Creates the tunnel + DNS route + a dedicated config
# file (it does NOT touch the shared ~/.cloudflared/config.yml used by other
# tunnels). After running, start the tunnel with the printed `run` command.
#
# Prereqs (already true on this machine): `cloudflared` installed and logged in
# (`cloudflared tunnel login` → ~/.cloudflared/cert.pem), and the domain added as
# a zone in the same Cloudflare account.
set -euo pipefail

TUNNEL_NAME="dec"
HOSTNAME="${1:-dec.visithink.net}"   # override: ./setup-cf-tunnel.sh dec.example.com
SERVICE="http://localhost:6390"   # DEC dev Worker (pnpm run dev → wrangler dev)
CF_DIR="${HOME}/.cloudflared"
CONFIG="${CF_DIR}/${TUNNEL_NAME}.yml"

echo "▶ Cloudflare tunnel setup: ${HOSTNAME} → ${SERVICE}"

# --- preflight -------------------------------------------------------------
command -v cloudflared >/dev/null || { echo "✗ cloudflared not installed"; exit 1; }
[ -f "${CF_DIR}/cert.pem" ] || { echo "✗ not logged in — run: cloudflared tunnel login"; exit 1; }

# --- 1. create the tunnel (skip if it already exists) ----------------------
UUID="$(cloudflared tunnel list --output json 2>/dev/null \
  | TUNNEL_NAME="${TUNNEL_NAME}" node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{const t=JSON.parse(d||"[]");const m=t.find(x=>x.name===process.env.TUNNEL_NAME);process.stdout.write(m?m.id:"")})')"

if [ -z "${UUID}" ]; then
  echo "▶ creating tunnel '${TUNNEL_NAME}'…"
  cloudflared tunnel create "${TUNNEL_NAME}"
  UUID="$(cloudflared tunnel list --output json 2>/dev/null \
    | TUNNEL_NAME="${TUNNEL_NAME}" node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{const t=JSON.parse(d||"[]");const m=t.find(x=>x.name===process.env.TUNNEL_NAME);process.stdout.write(m?m.id:"")})')"
else
  echo "✓ tunnel '${TUNNEL_NAME}' already exists (${UUID})"
fi
[ -n "${UUID}" ] || { echo "✗ could not determine tunnel UUID"; exit 1; }

CREDS="${CF_DIR}/${UUID}.json"
[ -f "${CREDS}" ] || { echo "✗ credentials file missing: ${CREDS}"; exit 1; }

# --- 2. write a DEDICATED config (never overwrite the shared config.yml) ----
echo "▶ writing ${CONFIG}"
cat > "${CONFIG}" <<EOF
# DEC dev tunnel — generated by scripts/setup-cf-tunnel.sh. Safe to edit.
tunnel: ${UUID}
credentials-file: ${CREDS}
ingress:
  - hostname: ${HOSTNAME}
    service: ${SERVICE}
  - service: http_status:404
EOF

# --- 3. route DNS (creates CNAME ${HOSTNAME} → ${UUID}.cfargotunnel.com) ----
# Outward change to the visithink.net zone. Idempotent: re-pointing an existing
# record to the same tunnel is fine; if it errors because the name is taken by an
# unrelated record, fix it in the dashboard.
echo "▶ routing DNS ${HOSTNAME} → tunnel…"
cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" 2>&1 | tee /tmp/dec-route.log || \
  echo "  (route may already exist — continuing)"

# --- 3b. sanity-check the route landed in the RIGHT zone --------------------
# `cloudflared tunnel route dns` needs a login cert (~/.cloudflared/cert.pem)
# authorized for the hostname's zone. If the cert is scoped to a DIFFERENT zone,
# cloudflared silently appends the hostname onto that zone (e.g.
# "${HOSTNAME}.other-zone.com") instead of failing. Detect that.
if grep -q "Added CNAME" /tmp/dec-route.log && ! grep -q "Added CNAME ${HOSTNAME} " /tmp/dec-route.log; then
  WRONG="$(grep -o 'Added CNAME [^ ]*' /tmp/dec-route.log | awk '{print $3}')"
  cat <<EOF

✗ DNS landed in the WRONG zone: ${WRONG}
  Your ~/.cloudflared/cert.pem is not authorized for ${HOSTNAME#*.}.
  Fix it one of two ways, then re-run this script:

  (a) Re-login scoped to the right zone (then re-run — idempotent):
        cloudflared tunnel login        # pick ${HOSTNAME#*.} in the browser

  (b) Or add the DNS record manually in the dashboard (no re-login):
        Zone ${HOSTNAME#*.} → DNS → Add record
          Type=CNAME  Name=${HOSTNAME%%.*}  Proxy=ON (orange)
          Target=${UUID}.cfargotunnel.com

  Also delete the junk record '${WRONG}' from its zone's DNS.
EOF
  exit 1
fi

# --- done ------------------------------------------------------------------
cat <<EOF

✓ Setup complete.

  Run the tunnel (keep it alive):
    cloudflared tunnel --config ${CONFIG} run ${TUNNEL_NAME}

  Start the app in another terminal:
    cd web-dec && pnpm run dev        # Worker on :6390

  ChatGPT connector URL:
    https://${HOSTNAME}/mcp

  Always-on (optional, survives reboot):
    sudo cloudflared --config ${CONFIG} service install
EOF
